### ISSUE TITLE
teacher_model/256px_full_size.pt

### ISSUE THREAD

**Issue by hqy-hub** [jiwoogit/DCP-GAN#3]
what is the teacher_model/256px_full_size.pt and dcp_0.7_256px_a5.0_n10_t1.00_model.pt means？

**Comment by jiwoogit** [comment]
1. The file `teacher_model/256px_full_size.pt` follows the naming convention established by the baseline (CAGAN). It represents the teacher checkpoint.

2. The file `dcp_0.7_256px_a5.0_n10_t1.00_model.pt` uses the following naming convention:
   - `0.7`: Pruning ratio ($p_r=0.7$)
   - `256px`: Model resolution
   - `a5.0`: $\alpha=0.5$, the strength of perturbations
   - `n10`: $N=10$, the number of perturbation directions
   - `t1.00`: Ratio of the truncation trick in the channel pruning stage (1.0 indicates no truncation).

It represents the initial student checkpoint after the channel pruning stage.
For detailed descriptions of each parameter, please refer to the paper.

Thank you.
